### ISSUE TITLE
ProblemStatement

### ISSUE THREAD

**Issue by karolserkis** [karolserkis/CAS-741-Pendula#1]
First issue created to review Problem Statement.
[Problem Statement](https://github.com/karolserkis/CAS-741-Pendula/blob/master/Doc/ProblemStatement/ProblemStatement.pdf)

**Comment by smiths** [comment]
@karolserkis, please address the (minor) comments in commit 1329fbd.  Once this is done, we can close this issue.

**Comment by karolserkis** [comment]
Could not compile .bib and could not compile  \newcommand{\authornote}[3]{}
Commented out and made other changes requested. 
Closing issue.

**Comment by karolserkis** [comment]
P.S. I also could not compile .bib for SRS.tex
I will need to try to start all over again with the blank template or if no success, reinstall all the TeX software.
What other issue do we need to open for SRS that is due on Oct 11th?
