### ISSUE TITLE
SRS Review 19

### ISSUE THREAD

**Issue by Malavika-Srinivasan** [karolserkis/CAS-741-Pendula#20]
@karolserkis 
Data Constraints

Please add the table which you discuss in the text below Data Constraints section.

The data constraints on the input and output variables, respectively. The column for physical
constraints gives the physical limitations on the range of values that can be taken by the
variable. The column for software constraints restricts the range of inputs to reasonable
values. The constraints are conservative, to give the user of the model the 
exibility to
experiment with unusual situations. The column of typical values is intended to provide a
feel for a common scenario. The uncertainty column provides an estimate of the condence
with which the physical quantities can be measured. This information would be part of the
input if one were performing an uncertainty quantication exercise.

**Comment by karolserkis** [comment]
@Malavika-Srinivasan @smiths 
Thanks for the great feedback!
