### ISSUE TITLE
SRS review 2

### ISSUE THREAD

**Issue by Malavika-Srinivasan** [karolserkis/CAS-741-Pendula#3]
@karolserkis 

Your figure caption for figure 1 says the following:

A simple gravity double pendulum (model assumes no friction or air resistance)[1]

1. I am not sure if you need to write "model assumes no ....". This should go in assumptions
2. [1] is not a reference. If you are trying to number the figures, that is not necessary as latex takes care of it. If you have a reason for this caption to be this way, please don't bother.

**Comment by karolserkis** [comment]
@Malavika-Srinivasan @smiths 
Thanks!
