### ISSUE TITLE
[MG Review] Minor Comments

### ISSUE THREAD

**Issue by hananezlitni** [karolserkis/CAS-741-Pendula#33]
**Minor Comments**

- Closing bracket missing in UC3.

- Missing references in page 1, beginning of page 4 and in page 7 - they’re marked with “?”.

- Typo in 6.3.5 - should be "Lagrangian" instead of "Lagrangiam".

- "References" section should start in a new page.

**Comment by karolserkis** [comment]
@hananezlitni @smiths 
Thanks!
