### ISSUE TITLE
[MG Review] Relationship between M3 (6.2.2) and M8 (6.3.4)

### ISSUE THREAD

**Issue by hananezlitni** [karolserkis/CAS-741-Pendula#34]
After reading the module decomposition of M3 (6.2.2) and M8 (6.3.4), they sounded very similar - both provide the GUI of the software. Also, I don't think that you should combine the GUI (buttons and other components that the user interacts with) and the plotting module in one (like in M8).

I suggest that you move the explanation about the interface (GUI) in M8 to M3, and change M8 to "Plotting Module", which hides the plot function.

**Comment by karolserkis** [comment]
@hananezlitni @smiths
Thanks for the good feedback!
