### ISSUE TITLE
[MG Review] Uses Hierarchy

### ISSUE THREAD

**Issue by hananezlitni** [karolserkis/CAS-741-Pendula#35]
I think that some use relationships are reversed for some modules.

For example, I think that the Hamiltonian and Lagrangian modules (M5 and M6) should use the user input module (M4), and not the opposite. 

What may help is to construct the hierarchy from bottom-up. That way, it would be clearer which module uses the other.

**Comment by karolserkis** [comment]
@hananezlitni @smiths 
Thanks for the feedback! Fixed.
