### ISSUE TITLE
MIS - questions about the data object

### ISSUE THREAD

**Issue by PeaWagon** [karolserkis/CAS-741-Pendula#37]
What methods does your data object support (see section 8.4.1 where you have data : object)? Is this the same as the data structure module (Section 11)? 

For section 11, does the format specify the pixels for an image, or does it specify the points to plot on a graph (where the image is constructed by an external graphing software)? If it is pixels, what are your parameters? Are they black and white pixels or coloured pixels?

**Comment by karolserkis** [comment]
@PeaWagon @smiths 
Thanks for the great feedback!
Resolved.
