### ISSUE TITLE
MIS - questions about the general program inputs and operators

### ISSUE THREAD

**Issue by PeaWagon** [karolserkis/CAS-741-Pendula#38]
What does your Hamiltonian look like? Is it a matrix or an array? What are its dimensions? Same for the lagrangian.

Section 8.4.4 under exception for verify_Input(). What does NotReal mean - do you mean that the function returns an integer? Also does the special character "I" have any meaning (after there exists symbol)? What does it mean for a string input to be out of bounds?

It was my understanding that we had to put the variables into the parentheses of each function in the access routine semantics. For example, the verify_Input function accepts a str and an int as inputs, but I don't see an integer or str in the function description. I also don't know what the int or str represent.

**Comment by karolserkis** [comment]
@PeaWagon @smiths 
Thanks for the great feedback!
