### ISSUE TITLE
MIS - couple of incomplete sentences and labels missing

### ISSUE THREAD

**Issue by PeaWagon** [karolserkis/CAS-741-Pendula#39]
Section 6.4.4 under run_mps transition: should say "... the data structure **is passed** through the modules for calculation."

Section 7 : "Methods to interact with user to make run Multi-Pendulum Simulation" is a sentence fragment.

Put labels on your sections so you can enable links within the text (\label{section-label}). These labels mean you can reference sections (\ref{section-label}) in the text. If you add a section and you have the labels, you don't have to renumber everything by hand (which takes a long time and is more error prone).

**Comment by karolserkis** [comment]
@PeaWagon @smiths 
Thanks for the valuable feedback!
Resolved.
