### ISSUE TITLE
Unit VnV Plan Peer Review 3 (section 4 and 5)

### ISSUE THREAD

**Issue by whitere123** [karolserkis/CAS-741-Pendula#46]
Hello @karolserkis , 

This issue is related to sections 4 and 5 of your document. 

- In section 4.4 it sounds unprofessional to say "prof smith". 
- I think it would be a good idea to provide some more detail in section 4.2. Perhaps you could explain the structure of the automated tests (ie cycle through an array of data and check an assert statement)
- I do not understand test-Inparams. You say that you are testing values yet the input table is a list of symbols not values. Also the tables should go into the appendix. There is a bit of a contradiction: in test case derivation you mention testing for negative numbers and than you proceed to talk about specific integers that you are verifying, where are they? 
- Also the beginning of the other tests 5.1.2 and onwards start with the same blurb as 5.1.1 … They also reference a table of symbols for input

**Comment by karolserkis** [comment]
@whitere123 @smiths 
Thanks for the feedback!
