### ISSUE TITLE
Unit VnV Plan peer edit 4 (appendix)

### ISSUE THREAD

**Issue by whitere123** [karolserkis/CAS-741-Pendula#47]
Hello @karolserkis , 

This issue is regarding the appendix in your unit VnVPlan. 

- I think that the appendix ( and entire document) is missing an input table with numbers that you plan to test the software with. 
- The checklist does not seem complete. You should add some more questions. 
- The usability survey questions should be modified. The last question does not make any sense to me. What do you mean by accept input? Do you mean input within constraints (because you should have tests that check for expceptions in the system vnv report) acting nicely? Or do you mean that any unexpected expections weren't thrown? it was not too clear.

**Comment by karolserkis** [comment]
@whitere123 @smiths 
Thanks for he excellent feedback!
