### ISSUE TITLE
Unit VnV plan Peer edit 5 (miscellaneous)

### ISSUE THREAD

**Issue by whitere123** [karolserkis/CAS-741-Pendula#48]
Hello @karolserkis , 

This issue is regarding some minor issues scattered throughout the unit vnv. 

- I believe there is only one e at the end of Poincare (with an accent on e) . Test-plotting-poincaree has two es . Sometimes you forget the accent. 
- If you decide to keep the list of modules in the unitvnv document than you should reference them throughout the tests. 
- In 4.3 maybe you want to list the specific functions from the link that are useful for your tests. This way the reader doesn't have to scan through all of them (ie in my case I only needed 2, so I listed them).

This is my last edit. Overall, well done! Good luck on your final documentation and enjoy your holidays!

**Comment by karolserkis** [comment]
@whitere123 @smiths 
Thanks for the great feedback.
